//
//  main.swift
//  sgetdata
//
//  Created by Brandon Plank on 7/6/21.
//

import Foundation
import ArgumentParser
import RNCryptor

extension Array where Element == UInt8 {
    func changed(orig: [UInt8]) -> Bool {
        if(orig == self){
            return false
        }
        return true
    }
}

extension Data {
    func changed(orig: Data) -> Bool {
        if(orig == self){
            return false
        }
        return true
    }
}

struct sgetdata: ParsableCommand {
    static let configuration = CommandConfiguration(
        abstract: "A Swift command-line tool to get raw data into swift [UInt8](byte) format"
    )
    
    @Flag(name: [.customLong("verbose"), .customShort("v")], help: "Show extra logging for debugging purposes")
    var verbose = false
    
    @Option(name: [.customLong("string"), .customShort("s")], help: "Specifies that you are using a string.")
    var string: String?
    
    @Option(name: [.customLong("file"), .customShort("f")], help: "Specifies that you are using a file.")
    var file: String?
    
    @Flag(name: [.customLong("compress"), .customShort("c")], help: "Compress the data to save some space, uses lzma.")
    var compress = false
    
    @Option(name: [.customLong("output"), .customShort("o")], help: "Specifies the output file to put the code in.")
    var output: String?
    
    @Option(name: [.customLong("encrypt"), .customShort("e")], help: "Encrypt data using AES256 encrytion with a passkey.")
    var encrypt: String?
    
    func run() throws {
        var arrayContents = ""
        var byte = [UInt8]()
        var data: Data? = nil
        
        //Grab the data
        if((string) != nil){
            data = (string?.data(using: .utf8))!
        } else if((file) != nil){
            let fileUrl = URL(fileURLWithPath: file!)
            do {
                data = try Data(contentsOf: fileUrl)
            } catch {
                print("Swift get data ran into an error: \(error)")
                throw ExitCode.failure
            }
        } else {
            throw ExitCode.failure
        }
        
        // Convert data to byte array
        byte = [UInt8](data!)
        
        // save for later to run some checks
        var oldDataTest = data
        var oldByteTest = byte
        
        if compress {
            do {
                let cData = try (data! as NSData).compressed(using: .lzfse)
                data = cData as Data
                if !data!.changed(orig: oldDataTest!) {
                    print("Error updating data structures")
                    throw ExitCode.failure
                }
                byte = [UInt8](data!)
                if !byte.changed(orig: oldByteTest) {
                    print("Error updating byte structures")
                    throw ExitCode.failure
                }
                // use your compressed data
            } catch {
                print("Error compressing data!")
                throw ExitCode.failure
            }
        }
        
        // Make sure everything is up-to-date
        oldByteTest = byte
        oldDataTest = data
        
        if encrypt != nil {
            let encryptedData = RNCryptor.encrypt(data: data!, withPassword: encrypt!)
            data = encryptedData as Data
            if !data!.changed(orig: oldDataTest!) {
                print("Error updating data structures")
                throw ExitCode.failure
            }
            byte = [UInt8](data!)
            if !byte.changed(orig: oldByteTest) {
                print("Error updating byte structures")
                throw ExitCode.failure
            }
        }
        
        #if DEBUG
        print("Start debug -> ASCII-REP:")
        print("======================")
        print("Bytes: \(byte.count)")
        print("Size of data: \(Double(byte.count/1000))KB")
        print("======================")
        for i in 0..<byte.count {
            print(String(format: "%c", byte[i]), terminator: "")
            if i == byte.count - 1{
                print("")
            }
        }
        print("======================")
        print("End debug")
        #endif
        
        arrayContents = byte.map { String(format: "0x%02x", $0) }.joined(separator: ", ")
        
        let now = Date()
        let formatter = DateFormatter()
        formatter.dateStyle = .full
        formatter.timeStyle = .full
        let dateTime = formatter.string(from: now)
        if arrayContents == ""{
            arrayContents = "Error with data"
        }
        let formatterYear = DateFormatter()
        formatterYear.setLocalizedDateFormatFromTemplate("yyyy")
        let outString = """
//
//  Auto generated by sgetdata on \(dateTime)
//  sgetdata
//
//  Copyright Brandon Plank \(formatterYear.string(from: now)).
//

let data:[UInt8] = [\(arrayContents)]
"""
        if((output) != nil){
            if output!.contains(".swift"){
                do {
                    try outString.write(to: URL(fileURLWithPath: output!), atomically: true, encoding: String.Encoding.utf8)
                    print("Saved file to: \(output!)")
                } catch {
                    print("Bad file path!")
                    throw ExitCode.failure
                }
            } else {
                print("Must save as a .swift file!")
                throw ExitCode.failure
            }
            return
        } else {
            print(outString)
        }
    }
}

sgetdata.main()

