# This is a basic workflow that is manually triggered
name: CI
on:
  push: {}
  pull_request: {}
jobs:
  run:
    runs-on: macOS-latest
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["12"]
    steps:
    - uses: actions/checkout@master
    - name: Set Xcode
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing Xcode_${{ matrix.xcode }}.app"
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version
        swift --version
        swift package --version
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p
    - name: Show Build Settings
      run: xcodebuild -project sgetdata.xcodeproj -scheme 'sgetdata' -showBuildSettings
    - name: Show Build SDK
      run: xcodebuild -project sgetdata.xcodeproj -scheme 'sgetdata' -showsdks
    - name: Show Available Destinations
      run: xcodebuild -project sgetdata.xcodeproj -scheme 'sgetdata' -showdestinations
    - name: Build and Package
      run: |
        mkdir temp/
        mkdir temp/Debug
        mkdir temp/Release
        xcodebuild clean build -project sgetdata.xcodeproj -scheme 'sgetdata' -destination 'platform=macOS' -showBuildTimingSummary CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -configuration Debug
        mv build/Products/Debug/sgetdata temp/Debug
        xcodebuild clean build -project sgetdata.xcodeproj -scheme 'sgetdata' -destination 'platform=macOS' -showBuildTimingSummary CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -configuration Release
        mv build/Products/Release/sgetdata temp/Release
        zip -r sgetdata-Artifacts.zip temp/
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: temp/*.zip
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*/*.zip
        tag: ${{ github.ref }}
        file_glob: true 
